config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :name, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark), status: :see_other
  end


  private

  def bookmark_params
    params.require(:bookmark).permit([:comment, :movie_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path(@list), notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<h1 class="title-form">Choose your movie</h1>

<%= simple_form_for ([@list, @bookmark]) do |f| %>
  <div class="form-control formulaire">
    <%= f.association :movie, label: "Movie" %>
    <%= f.input :comment, label: "Add your comment"%>
    <div class="form-actions button m-0">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMoviesList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%=root_path%>">
          <img src="https://pbs.twimg.com/profile_images/919840810899726336/uLCbvVus_400x400.jpg"/>
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%=root_path%>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=new_list_path%>">New list</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_category.html.erb
<div class="cards">
  <% @lists.each do |list| %>
    <div class="card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.photo.key) if list.photo.attached? %>')">
        <%= link_to list.name, list_path(list) %>
        <%= link_to "+", list_path(list), data: { turbo_method: :delete, turbo_confirm: "Delete this category?" }, class: "card-remove-link" %>
    </div>
  <% end %>

  <div class="card-category m-3 cards"
       style="background-color: #986079">
       <%= link_to "New list", new_list_path %>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <div class="form-control formulaire">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <div class="form-actions button m-0">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/lists/index.html.erb
<%# ------------  banner -----------%>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1325&q=80);">
  <div class="container">
    <h1>My movie list</h1>
    <p> Save any kind of movies</p>
  </div>
</div>

<%= render 'category', list: @list %>

<%# ------------  Button to create a new list -----------%>

</div>

app/views/lists/new.html.erb
<h1 class="title-form">Create a list</h1>
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key if @list.photo.attached? %>');">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <a><%= link_to "Back", root_path, class:"button btn btn-dark mt-4"%></a>
  <a><%= link_to 'Add movie', new_list_bookmark_path(@list), class:"button-add btn btn-dark mt-4"%></a>
  <div class="films">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card p-2 mt-4 position-relative rounded">
        <img src="<%= bookmark.movie.poster_url %>" class="films-category" alt="...">
        <div class="p-3">
          <h5><strong><%= bookmark.movie.name %></strong></h5>
          <p>(<%= bookmark.movie.year %>) <%= bookmark.movie.director %></p>
          <p class="overview"><%= bookmark.movie.overview %></p>
          <span class="position-absolute bottom-0 end-0"><%= bookmark.comment %></span>
          <div>
            <a><%= link_to 'x', bookmark_path(bookmark),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"delete position-absolute top-0 end-0"%></a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>